[package]
name = "dev-signer"
version = "0.1.0"
edition = "2024"
description = """
Software-only stand-in for nano-signer
"""

[dependencies]
token-core = { path = "../token-core", features = ["std"] }
slh-dsa = "0.1.0"
signature = "=2.3.0-pre.4"
rand_core = { version = "0.6.4", features = ["getrandom"] }
