[package]
edition      = "2024"
name         = "nano-signer"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "nano-signer"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32s3", "unstable"] }


esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3"] }

critical-section = "1.2.0"
# Forked locally from slh-dsa 0.2.0-rc.5 to add a hardware-SHA HashSuite
slh-dsa-hw = { path = "../slh-dsa-hw", default-features = false, features = ["hw-sha"] }
token-core = { path = "../token-core" }
nb = "1"


[features]
default = ["param-192f"]
param-128s = []
param-128f = []
param-192s = []
param-192f = []
param-256s = []
param-256f = []

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1     
debug         = 2     
lto           = 'fat'
opt-level     = 's'
